### ISSUE TITLE
Indirizzi italiani

### ISSUE THREAD

**Issue by lorenzoturrini** [L2PT/Flutter_organizer-app#26]
Auto completamento suggerisce solo indirizzi presenti in Italia. 
_HINT: controllare la parte server side su firebase_

**Comment by johnMinelli** [comment]
me vuoi solo indirizzi in italia o adesso è così e lo vuoi cambiare?
da getLocationsWeb()
`    String url = 'https://maps.googleapis.com/maps/api/place/autocomplete/json?input='+address+'&country=it&language=it&key='+Constants.googleMapsApiKey;
`

da getLocations()
`GooglePlace(Constants.googleMapsApiKey).autocomplete.get(address);
`
non so cosa faccia dietro

**Comment by lorenzoturrini** [comment]
> me vuoi solo indirizzi in italia o adesso è così e lo vuoi cambiare?
> da getLocationsWeb()
> ` String url = 'https://maps.googleapis.com/maps/api/place/autocomplete/json?input='+address+'&country=it&language=it&key='+Constants.googleMapsApiKey;`
> 
> da getLocations()
> `GooglePlace(Constants.googleMapsApiKey).autocomplete.get(address); `
> non so cosa faccia dietro

Quello che vogliono è che nei suggerimenti ci sia solo degli indirizzi italiani e non piu quelli esteri. Adesso sembra che questo filtro non ci sia. Questo avviene sia nel web sia nel mobile, in cui ci sono due funzionamenti differenti che sinceramente si possono unificare e utilizzare solo quello web ed eliminare la dipendenza del progetto a quella libreria ( DA ANALIZZARE)
