### ISSUE TITLE
Calendario orario ridotto

### ISSUE THREAD

**Issue by lorenzoturrini** [L2PT/Flutter_organizer-app#27]
Visualizzazione calendario responsabile orario di inizio 7 del mattino orario di fine 6 di sera. Aggiornare si la visualizzazione web che mobile.

**Comment by johnMinelli** [comment]
done and tested web and mobile

**Comment by lorenzoturrini** [comment]
> done and tested web and mobile

Quando riesci spostala in done e chiudi l issue, ci sta metteci il commento ma servono anche le altre due cose. 
Grazie mille

**Comment by johnMinelli** [comment]
mi avevi ripreso l'ultima volta che li avevo chiusi perchè dovevano essere confermati dal cliente prima...

**Comment by lorenzoturrini** [comment]
> mi avevi ripreso l'ultima volta che li avevo chiusi perchè dovevano essere confermati dal cliente prima...

Me ne ero dimenticato ma va bene cosi nel caso ne apro di nuovi o lo riapro.
